-- ============================================
-- WISDOM LIBRARY SEED DATA - PART 5 (FINAL)
-- Last 72 excerpts for 6 remaining books
-- Against Gods, Fooled by Randomness, Security Analysis,
-- Common Stocks, One Up Wall Street, Essays Buffett
-- ============================================

-- Against the Gods (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('against_the_gods', 1, 'História do Risco', 'History of Risk', 'Antes do Renascimento, futuro era domínio dos deuses. Matemática da probabilidade libertou humanidade do fatalismo. Agora podemos quantificar e gerenciar incerteza.', 'Before Renaissance, future was domain of gods. Probability mathematics freed humanity from fatalism. Now we can quantify and manage uncertainty.', 'Introdução', 'Matemática transformou risco de destino em escolha gerenciável.', 'Mathematics transformed risk from fate to manageable choice.'),
('against_the_gods', 2, 'Probabilidade', 'Probability', 'Probabilidade não prevê eventos específicos, mas padrões em longo prazo. Moeda pode cair cara 10 vezes seguidas, mas em 10.000 lançamentos será ~50%.', 'Probability doesn''t predict specific events, but long-term patterns. Coin can land heads 10 times in row, but in 10,000 flips will be ~50%.', 'Capítulo 3', 'Probabilidade funciona em longo prazo, não curto prazo.', 'Probability works long-term, not short-term.'),
('against_the_gods', 3, 'Distribuição Normal', 'Normal Distribution', 'Muitos fenômenos seguem curva em sino. Maioria dos resultados próximos à média, poucos extremos. Mas mercados financeiros não são normais - têm caudas gordas.', 'Many phenomena follow bell curve. Most outcomes near average, few extremes. But financial markets aren''t normal - they have fat tails.', 'Capítulo 6', 'Mercados têm mais eventos extremos que distribuição normal prevê.', 'Markets have more extreme events than normal distribution predicts.'),
('against_the_gods', 4, 'Teoria dos Jogos', 'Game Theory', 'Decisões ótimas dependem do que outros farão. Em investimentos, você compete contra outros investidores. Pense estrategicamente sobre comportamento alheio.', 'Optimal decisions depend on what others will do. In investing, you compete against other investors. Think strategically about others'' behavior.', 'Capítulo 9', 'Considere ações de outros participantes em decisões estratégicas.', 'Consider other participants'' actions in strategic decisions.'),
('against_the_gods', 5, 'Utilidade Esperada', 'Expected Utility', 'Valor não é linear. $1 milhão para pessoa pobre vale mais que para bilionário. Decisões devem considerar utilidade, não apenas valor monetário.', 'Value isn''t linear. $1 million to poor person is worth more than to billionaire. Decisions should consider utility, not just monetary value.', 'Capítulo 6', 'Utilidade marginal decrescente afeta decisões racionais.', 'Diminishing marginal utility affects rational decisions.'),
('against_the_gods', 6, 'Diversificação Moderna', 'Modern Diversification', 'Markowitz mostrou matematicamente como diversificação reduz risco. Combine ativos com correlações baixas. Portfólio pode ter menos risco que componentes individuais.', 'Markowitz showed mathematically how diversification reduces risk. Combine assets with low correlations. Portfolio can have less risk than individual components.', 'Capítulo 10', 'Diversificação científica reduz risco sem sacrificar retorno.', 'Scientific diversification reduces risk without sacrificing return.'),
('against_the_gods', 7, 'CAPM', 'CAPM', 'Capital Asset Pricing Model relaciona risco e retorno. Ativos mais arriscados devem oferecer retornos maiores. Beta mede risco relativo ao mercado.', 'Capital Asset Pricing Model relates risk and return. Riskier assets should offer higher returns. Beta measures risk relative to market.', 'Capítulo 11', 'Retorno esperado deve compensar risco assumido.', 'Expected return should compensate for risk taken.'),
('against_the_gods', 8, 'Opções e Derivativos', 'Options and Derivatives', 'Black-Scholes revolucionou precificação de opções. Derivativos permitem transferir risco. Ferramentas poderosas mas perigosas se mal usadas.', 'Black-Scholes revolutionized option pricing. Derivatives allow risk transfer. Powerful tools but dangerous if misused.', 'Capítulo 12', 'Derivativos são ferramentas de gestão de risco, não especulação.', 'Derivatives are risk management tools, not speculation.'),
('against_the_gods', 9, 'Incerteza vs. Risco', 'Uncertainty vs. Risk', 'Risco é quantificável (probabilidades conhecidas). Incerteza não é (probabilidades desconhecidas). Muitos eventos financeiros são incerteza, não risco.', 'Risk is quantifiable (known probabilities). Uncertainty isn''t (unknown probabilities). Many financial events are uncertainty, not risk.', 'Capítulo 13', 'Reconheça diferença entre risco mensurável e incerteza.', 'Recognize difference between measurable risk and uncertainty.'),
('against_the_gods', 10, 'Vieses Comportamentais', 'Behavioral Biases', 'Humanos não são racionais como modelos assumem. Vieses sistemáticos afetam decisões. Reconhecer vieses é primeiro passo para superá-los.', 'Humans aren''t rational as models assume. Systematic biases affect decisions. Recognizing biases is first step to overcoming them.', 'Capítulo 14', 'Modelos matemáticos ignoram irracionalidade humana real.', 'Mathematical models ignore real human irrationality.'),
('against_the_gods', 11, 'Gestão de Risco', 'Risk Management', 'Gestão de risco não elimina risco, mas torna-o gerenciável. Identifique riscos, quantifique quando possível, mitigue através de diversificação e hedging.', 'Risk management doesn''t eliminate risk, but makes it manageable. Identify risks, quantify when possible, mitigate through diversification and hedging.', 'Conclusão', 'Gerencie risco ativamente - não pode eliminá-lo completamente.', 'Manage risk actively - you can''t eliminate it completely.'),
('against_the_gods', 12, 'Futuro Incerto', 'Uncertain Future', 'Apesar de todo progresso matemático, futuro permanece incerto. Ferramentas ajudam mas não garantem. Humildade diante da incerteza é sabedoria.', 'Despite all mathematical progress, future remains uncertain. Tools help but don''t guarantee. Humility before uncertainty is wisdom.', 'Epílogo', 'Ferramentas matemáticas ajudam mas não eliminam incerteza.', 'Mathematical tools help but don''t eliminate uncertainty.');

-- Fooled by Randomness (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('fooled_by_randomness', 1, 'Sorte vs. Habilidade', 'Luck vs. Skill', 'Difícil distinguir sorte de habilidade em curto prazo. Trader sortudo parece habilidoso por anos. Apenas longo prazo revela verdade. Não confunda resultados com processos.', 'Hard to distinguish luck from skill short-term. Lucky trader looks skilled for years. Only long-term reveals truth. Don''t confuse outcomes with processes.', 'Capítulo 1', 'Resultados de curto prazo não revelam habilidade vs. sorte.', 'Short-term results don''t reveal skill vs. luck.'),
('fooled_by_randomness', 2, 'Histórias Alternativas', 'Alternative Histories', 'Para cada história de sucesso, há mil histórias alternativas de fracasso. Vencedor da loteria teve sorte, não habilidade. Considere caminhos não tomados.', 'For every success story, there are thousand alternative failure stories. Lottery winner had luck, not skill. Consider paths not taken.', 'Capítulo 3', 'Considere histórias alternativas possíveis, não apenas resultado real.', 'Consider possible alternative histories, not just actual outcome.'),
('fooled_by_randomness', 3, 'Viés de Sobrevivência', 'Survivorship Bias', 'Estudamos vencedores, ignoramos perdedores que desapareceram. Fundos ruins fecham, só bons permanecem em estatísticas. Isso distorce percepção de sucesso.', 'We study winners, ignore losers who disappeared. Bad funds close, only good remain in statistics. This distorts perception of success.', 'Capítulo 11', 'Lembre-se dos que falharam e não estão mais visíveis.', 'Remember those who failed and are no longer visible.'),
('fooled_by_randomness', 4, 'Ruído vs. Sinal', 'Noise vs. Signal', 'Maioria das flutuações diárias é ruído, não sinal. Quanto mais frequentemente você checa preços, mais ruído vê. Foque em tendências de longo prazo.', 'Most daily fluctuations are noise, not signal. The more frequently you check prices, the more noise you see. Focus on long-term trends.', 'Capítulo 4', 'Reduza frequência de monitoramento para ver sinal, não ruído.', 'Reduce monitoring frequency to see signal, not noise.'),
('fooled_by_randomness', 5, 'Assimetria de Resultados', 'Asymmetry of Outcomes', 'Pequena probabilidade de evento catastrófico pode destruir anos de ganhos. Evite estratégias com assimetria negativa. Proteja-se de ruína.', 'Small probability of catastrophic event can destroy years of gains. Avoid strategies with negative asymmetry. Protect yourself from ruin.', 'Capítulo 5', 'Evite estratégias que podem causar ruína, mesmo se raras.', 'Avoid strategies that can cause ruin, even if rare.'),
('fooled_by_randomness', 6, 'Ergodicity', 'Ergodicity', 'Média do grupo não é média individual ao longo do tempo. Cassino sempre ganha (média do grupo), mas jogador individual pode falir (média temporal). Entenda diferença.', 'Group average isn''t individual average over time. Casino always wins (group average), but individual gambler can go broke (time average). Understand difference.', 'Capítulo 7', 'Média do grupo ≠ média individual ao longo do tempo.', 'Group average ≠ individual average over time.'),
('fooled_by_randomness', 7, 'Jornalistas e Explicações', 'Journalists and Explanations', 'Mídia sempre oferece explicações para movimentos de mercado. "Mercado subiu porque...". Mas são narrativas pós-fato, não causas reais. Ignore ruído da mídia.', 'Media always offers explanations for market moves. "Market rose because...". But these are post-hoc narratives, not real causes. Ignore media noise.', 'Capítulo 10', 'Explicações da mídia são narrativas, não causas reais.', 'Media explanations are narratives, not real causes.'),
('fooled_by_randomness', 8, 'Skin in the Game', 'Skin in the Game', 'Confie apenas em quem tem algo a perder. Consultores sem skin in the game dão conselhos arriscados. Siga apenas quem arrisca próprio dinheiro.', 'Trust only those who have something to lose. Consultants without skin in game give risky advice. Follow only those who risk own money.', 'Capítulo 8', 'Confie em quem tem skin in the game, não apenas opiniões.', 'Trust those with skin in the game, not just opinions.'),
('fooled_by_randomness', 9, 'Stoicismo', 'Stoicism', 'Estoicos aceitam que não controlam resultados, apenas esforços. Foque no que pode controlar. Aceite aleatoriedade com equanimidade.', 'Stoics accept they don''t control outcomes, only efforts. Focus on what you can control. Accept randomness with equanimity.', 'Capítulo 12', 'Controle esforços, aceite que resultados têm aleatoriedade.', 'Control efforts, accept that outcomes have randomness.'),
('fooled_by_randomness', 10, 'Risco de Ruína', 'Risk of Ruin', 'Mesmo com vantagem estatística, risco de ruína pode destruir você. Gerencie tamanho de posições. Nunca arrisque tudo em uma aposta.', 'Even with statistical edge, risk of ruin can destroy you. Manage position sizes. Never risk everything on one bet.', 'Capítulo 6', 'Gerencie risco de ruína - sobrevivência vem primeiro.', 'Manage risk of ruin - survival comes first.'),
('fooled_by_randomness', 11, 'Opacidade Causal', 'Causal Opacity', 'Causas reais são opacas. Não sabemos por que mercados se movem. Narrativas são confortáveis mas enganosas. Aceite que não entendemos tudo.', 'Real causes are opaque. We don''t know why markets move. Narratives are comfortable but misleading. Accept that we don''t understand everything.', 'Capítulo 9', 'Aceite que causas reais são frequentemente opacas.', 'Accept that real causes are often opaque.'),
('fooled_by_randomness', 12, 'Raridade e Impacto', 'Rarity and Impact', 'Eventos raros têm impacto desproporcional. Não ignore apenas porque são raros. Prepare-se para o improvável. Cisnes negros existem.', 'Rare events have disproportionate impact. Don''t ignore just because they''re rare. Prepare for the improbable. Black swans exist.', 'Conclusão', 'Eventos raros importam mais que frequentes - prepare-se.', 'Rare events matter more than frequent ones - prepare.');

-- Security Analysis (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('security_analysis', 1, 'Análise Quantitativa', 'Quantitative Analysis', 'Análise começa com números: lucros, ativos, passivos, fluxo de caixa. Dados objetivos são fundação. Mas números sozinhos não bastam - contexto qualitativo importa.', 'Analysis begins with numbers: earnings, assets, liabilities, cash flow. Objective data is foundation. But numbers alone aren''t enough - qualitative context matters.', 'Parte 1', 'Combine análise quantitativa com julgamento qualitativo.', 'Combine quantitative analysis with qualitative judgment.'),
('security_analysis', 2, 'Valor Intrínseco', 'Intrinsic Value', 'Valor intrínseco é estimativa de valor verdadeiro baseado em fundamentos. Difere de preço de mercado. Objetivo é comprar quando preço < valor intrínseco.', 'Intrinsic value is estimate of true value based on fundamentals. Differs from market price. Goal is to buy when price < intrinsic value.', 'Capítulo 2', 'Estime valor intrínseco independente de preço de mercado.', 'Estimate intrinsic value independent of market price.'),
('security_analysis', 3, 'Títulos vs. Ações', 'Bonds vs. Stocks', 'Títulos têm prioridade legal sobre ações. Em falência, credores são pagos primeiro. Mas ações têm potencial de crescimento ilimitado. Balance segurança e crescimento.', 'Bonds have legal priority over stocks. In bankruptcy, creditors are paid first. But stocks have unlimited growth potential. Balance safety and growth.', 'Parte 2', 'Títulos oferecem segurança, ações oferecem crescimento.', 'Bonds offer safety, stocks offer growth.'),
('security_analysis', 4, 'Análise de Balanço', 'Balance Sheet Analysis', 'Balanço revela saúde financeira. Examine ativos (o que empresa possui), passivos (o que deve), patrimônio líquido (diferença). Liquidez e solvência são cruciais.', 'Balance sheet reveals financial health. Examine assets (what company owns), liabilities (what it owes), equity (difference). Liquidity and solvency are crucial.', 'Capítulo 9', 'Balanço patrimonial mostra solidez financeira da empresa.', 'Balance sheet shows company''s financial solidity.'),
('security_analysis', 5, 'Demonstração de Resultados', 'Income Statement', 'Demonstração de resultados mostra lucratividade. Receita menos despesas = lucro. Examine margens, tendências, qualidade dos lucros. Lucros consistentes são valiosos.', 'Income statement shows profitability. Revenue minus expenses = profit. Examine margins, trends, earnings quality. Consistent earnings are valuable.', 'Capítulo 10', 'Demonstração de resultados revela capacidade de gerar lucro.', 'Income statement reveals profit-generating ability.'),
('security_analysis', 6, 'Fluxo de Caixa', 'Cash Flow', 'Lucro contábil pode ser manipulado. Fluxo de caixa é mais confiável. Empresa pode ter lucro mas sem caixa. Analise fluxo de caixa operacional.', 'Accounting profit can be manipulated. Cash flow is more reliable. Company can have profit but no cash. Analyze operating cash flow.', 'Capítulo 11', 'Fluxo de caixa é mais confiável que lucro contábil.', 'Cash flow is more reliable than accounting profit.'),
('security_analysis', 7, 'Índices Financeiros', 'Financial Ratios', 'Índices revelam padrões: P/L, P/VPA, ROE, margem líquida, dívida/patrimônio. Compare com histórico e concorrentes. Nenhum índice conta história completa.', 'Ratios reveal patterns: P/E, P/B, ROE, net margin, debt/equity. Compare with history and competitors. No single ratio tells complete story.', 'Capítulo 12', 'Use múltiplos índices para análise completa.', 'Use multiple ratios for complete analysis.'),
('security_analysis', 8, 'Qualidade dos Lucros', 'Earnings Quality', 'Nem todos lucros são iguais. Lucros recorrentes valem mais que extraordinários. Examine notas de rodapé, políticas contábeis. Desconfie de ajustes frequentes.', 'Not all earnings are equal. Recurring earnings worth more than extraordinary. Examine footnotes, accounting policies. Distrust frequent adjustments.', 'Capítulo 13', 'Qualidade dos lucros importa tanto quanto quantidade.', 'Earnings quality matters as much as quantity.'),
('security_analysis', 9, 'Análise Setorial', 'Industry Analysis', 'Contexto setorial importa. Empresa excelente em setor ruim pode falhar. Examine competição, regulação, ciclos econômicos, barreiras de entrada.', 'Industry context matters. Excellent company in bad industry can fail. Examine competition, regulation, economic cycles, barriers to entry.', 'Capítulo 15', 'Analise setor antes de analisar empresa individual.', 'Analyze industry before analyzing individual company.'),
('security_analysis', 10, 'Gestão', 'Management', 'Gestão competente e honesta é crucial. Examine histórico, alocação de capital, transparência. Desconfie de promessas grandiosas e falta de transparência.', 'Competent and honest management is crucial. Examine track record, capital allocation, transparency. Distrust grandiose promises and lack of transparency.', 'Capítulo 16', 'Qualidade da gestão é fator crítico de sucesso.', 'Management quality is critical success factor.'),
('security_analysis', 11, 'Vantagem Competitiva', 'Competitive Advantage', 'Empresas com vantagens competitivas sustentáveis (moats) mantêm lucratividade. Examine marca, patentes, economias de escala, efeitos de rede.', 'Companies with sustainable competitive advantages (moats) maintain profitability. Examine brand, patents, economies of scale, network effects.', 'Capítulo 17', 'Vantagens competitivas sustentáveis protegem lucratividade.', 'Sustainable competitive advantages protect profitability.'),
('security_analysis', 12, 'Conservadorismo', 'Conservatism', 'Seja conservador em estimativas. Melhor subestimar que superestimar. Margem de segurança compensa erros. Pessimismo prudente protege capital.', 'Be conservative in estimates. Better to underestimate than overestimate. Margin of safety compensates for errors. Prudent pessimism protects capital.', 'Conclusão', 'Conservadorismo em análise protege contra erros.', 'Conservatism in analysis protects against errors.');

-- Common Stocks and Uncommon Profits (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('common_stocks_uncommon_profits', 1, 'Scuttlebutt', 'Scuttlebutt', 'Converse com clientes, fornecedores, ex-funcionários, concorrentes. Informações de campo revelam mais que relatórios. Pesquisa primária supera análise de mesa.', 'Talk to customers, suppliers, ex-employees, competitors. Field information reveals more than reports. Primary research beats desk analysis.', 'Capítulo 2', 'Pesquisa de campo revela insights que números não mostram.', 'Field research reveals insights that numbers don''t show.'),
('common_stocks_uncommon_profits', 2, '15 Pontos', 'Fifteen Points', 'Avalie empresas em 15 critérios: potencial de mercado, P&D, vendas, margens, relações trabalhistas, gestão, etc. Empresa deve pontuar bem em todos.', 'Evaluate companies on 15 criteria: market potential, R&D, sales, margins, labor relations, management, etc. Company should score well on all.', 'Capítulo 3', 'Use checklist abrangente para avaliar qualidade empresarial.', 'Use comprehensive checklist to evaluate company quality.'),
('common_stocks_uncommon_profits', 3, 'Crescimento', 'Growth', 'Foque em empresas com potencial de crescimento acima da média por anos. Crescimento sustentável cria riqueza. Evite empresas maduras sem crescimento.', 'Focus on companies with above-average growth potential for years. Sustainable growth creates wealth. Avoid mature companies without growth.', 'Capítulo 4', 'Crescimento sustentável de longo prazo é chave.', 'Sustainable long-term growth is key.'),
('common_stocks_uncommon_profits', 4, 'P&D', 'R&D', 'Empresas que investem em P&D mantêm vantagem competitiva. Inovação é crucial em mercados dinâmicos. Examine gastos e resultados de P&D.', 'Companies investing in R&D maintain competitive advantage. Innovation is crucial in dynamic markets. Examine R&D spending and results.', 'Capítulo 5', 'Investimento em P&D sustenta vantagem competitiva.', 'R&D investment sustains competitive advantage.'),
('common_stocks_uncommon_profits', 5, 'Vendas e Marketing', 'Sales and Marketing', 'Organização de vendas eficaz é crucial. Produto excelente sem vendas não gera lucro. Avalie força e eficácia da equipe de vendas.', 'Effective sales organization is crucial. Excellent product without sales doesn''t generate profit. Assess sales team strength and effectiveness.', 'Capítulo 6', 'Vendas eficazes são tão importantes quanto produto.', 'Effective sales are as important as product.'),
('common_stocks_uncommon_profits', 6, 'Margens de Lucro', 'Profit Margins', 'Margens altas indicam vantagem competitiva. Empresas com margens crescentes são valiosas. Examine tendência de margens ao longo do tempo.', 'High margins indicate competitive advantage. Companies with growing margins are valuable. Examine margin trends over time.', 'Capítulo 7', 'Margens crescentes sinalizam vantagem competitiva forte.', 'Growing margins signal strong competitive advantage.'),
('common_stocks_uncommon_profits', 7, 'Relações Trabalhistas', 'Labor Relations', 'Boas relações com funcionários aumentam produtividade. Empresas com alta rotatividade têm problemas. Examine cultura e satisfação dos funcionários.', 'Good employee relations increase productivity. Companies with high turnover have problems. Examine culture and employee satisfaction.', 'Capítulo 8', 'Relações trabalhistas positivas impulsionam desempenho.', 'Positive labor relations drive performance.'),
('common_stocks_uncommon_profits', 8, 'Gestão Executiva', 'Executive Management', 'Gestão determina sucesso. Examine integridade, visão, execução. Gestores que admitem erros são mais confiáveis que os que sempre culpam outros.', 'Management determines success. Examine integrity, vision, execution. Managers who admit mistakes are more trustworthy than those who always blame others.', 'Capítulo 9', 'Qualidade da gestão é fator determinante de sucesso.', 'Management quality is determining factor of success.'),
('common_stocks_uncommon_profits', 9, 'Profundidade Gerencial', 'Management Depth', 'Empresa não pode depender de uma pessoa. Examine profundidade do time gerencial. Sucessão planejada indica organização madura.', 'Company can''t depend on one person. Examine management team depth. Planned succession indicates mature organization.', 'Capítulo 10', 'Profundidade gerencial protege contra risco de pessoa-chave.', 'Management depth protects against key-person risk.'),
('common_stocks_uncommon_profits', 10, 'Controles Financeiros', 'Financial Controls', 'Controles internos eficazes previnem fraudes e desperdícios. Examine sistemas de controle, auditoria, governança. Transparência é sinal positivo.', 'Effective internal controls prevent fraud and waste. Examine control systems, audit, governance. Transparency is positive sign.', 'Capítulo 11', 'Controles financeiros robustos protegem acionistas.', 'Robust financial controls protect shareholders.'),
('common_stocks_uncommon_profits', 11, 'Quando Vender', 'When to Sell', 'Venda apenas se: 1) Errou na análise inicial, 2) Empresa deteriorou fundamentalmente, 3) Encontrou oportunidade muito melhor. Não venda por flutuações de preço.', 'Sell only if: 1) You were wrong in initial analysis, 2) Company deteriorated fundamentally, 3) You found much better opportunity. Don''t sell for price fluctuations.', 'Capítulo 12', 'Venda por razões fundamentais, não flutuações de preço.', 'Sell for fundamental reasons, not price fluctuations.'),
('common_stocks_uncommon_profits', 12, 'Paciência', 'Patience', 'Grandes retornos vêm de manter empresas excelentes por anos. Não venda vencedores cedo demais. Paciência é virtude mais valiosa em investimentos.', 'Great returns come from holding excellent companies for years. Don''t sell winners too early. Patience is most valuable virtue in investing.', 'Conclusão', 'Paciência com empresas de qualidade gera retornos extraordinários.', 'Patience with quality companies generates extraordinary returns.');

-- One Up On Wall Street (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('one_up_on_wall_street', 1, 'Invista no Que Conhece', 'Invest in What You Know', 'Melhores ideias vêm de sua vida diária. Você vê produtos populares antes de Wall Street. Use vantagem de consumidor. Invista em empresas cujos produtos você entende e usa.', 'Best ideas come from your daily life. You see popular products before Wall Street. Use consumer advantage. Invest in companies whose products you understand and use.', 'Capítulo 1', 'Vantagem do investidor individual está em observação diária.', 'Individual investor advantage is in daily observation.'),
('one_up_on_wall_street', 2, 'Seis Categorias', 'Six Categories', 'Empresas caem em 6 categorias: crescimento lento, stalwarts, crescimento rápido, cíclicas, turnaround, ativos ocultos. Cada requer estratégia diferente.', 'Companies fall into 6 categories: slow growers, stalwarts, fast growers, cyclicals, turnarounds, asset plays. Each requires different strategy.', 'Capítulo 4', 'Identifique categoria da empresa para definir estratégia.', 'Identify company category to define strategy.'),
('one_up_on_wall_street', 3, 'Tenbaggers', 'Tenbaggers', 'Procure ações que podem multiplicar 10x. Pequenas empresas em crescimento têm maior potencial. Uma tenbagger compensa várias perdas.', 'Look for stocks that can multiply 10x. Small growing companies have greatest potential. One tenbagger compensates for several losses.', 'Capítulo 5', 'Uma ação que multiplica 10x compensa muitos erros.', 'One stock that multiplies 10x compensates for many mistakes.'),
('one_up_on_wall_street', 4, 'Evite Empresas Quentes', 'Avoid Hot Companies', 'Empresas mais comentadas raramente são melhores investimentos. Mídia cria hype. Procure empresas entediantes que ninguém cobre. Menos competição.', 'Most talked-about companies are rarely best investments. Media creates hype. Look for boring companies nobody covers. Less competition.', 'Capítulo 6', 'Empresas entediantes frequentemente superam as glamorosas.', 'Boring companies often outperform glamorous ones.'),
('one_up_on_wall_street', 5, 'Histórias Simples', 'Simple Stories', 'Se não consegue explicar empresa para criança de 10 anos em 2 minutos, não invista. Simplicidade é virtude. Complexidade esconde problemas.', 'If you can''t explain company to 10-year-old in 2 minutes, don''t invest. Simplicity is virtue. Complexity hides problems.', 'Capítulo 7', 'Invista apenas em negócios que você entende claramente.', 'Invest only in businesses you clearly understand.'),
('one_up_on_wall_street', 6, 'P/L e Crescimento', 'P/E and Growth', 'Compare P/L com taxa de crescimento (PEG ratio). PEG < 1 é atraente. Empresa crescendo 20% com P/L de 15 é melhor que crescendo 10% com P/L de 15.', 'Compare P/E with growth rate (PEG ratio). PEG < 1 is attractive. Company growing 20% with P/E of 15 is better than growing 10% with P/E of 15.', 'Capítulo 11', 'PEG ratio ajuda avaliar se crescimento justifica preço.', 'PEG ratio helps assess if growth justifies price.'),
('one_up_on_wall_street', 7, 'Balanço Patrimonial', 'Balance Sheet', 'Examine dívida. Empresas com pouca ou nenhuma dívida sobrevivem crises. Dívida alta é perigosa em recessões. Prefira balanços sólidos.', 'Examine debt. Companies with little or no debt survive crises. High debt is dangerous in recessions. Prefer solid balance sheets.', 'Capítulo 12', 'Baixa dívida protege empresa em tempos difíceis.', 'Low debt protects company in difficult times.'),
('one_up_on_wall_street', 8, 'Fluxo de Caixa Livre', 'Free Cash Flow', 'Fluxo de caixa livre (caixa operacional - capex) é crucial. Empresas que geram caixa podem investir, pagar dividendos, recomprar ações. Examine tendência.', 'Free cash flow (operating cash - capex) is crucial. Companies generating cash can invest, pay dividends, buy back stock. Examine trend.', 'Capítulo 13', 'Geração consistente de caixa livre é sinal de qualidade.', 'Consistent free cash flow generation is quality sign.'),
('one_up_on_wall_street', 9, 'Recompra de Ações', 'Stock Buybacks', 'Recompra de ações reduz quantidade de ações, aumentando lucro por ação. Sinal de que gestão acredita em empresa. Mas só é bom se preço é razoável.', 'Stock buybacks reduce share count, increasing earnings per share. Sign that management believes in company. But only good if price is reasonable.', 'Capítulo 14', 'Recompras a preços razoáveis beneficiam acionistas.', 'Buybacks at reasonable prices benefit shareholders.'),
('one_up_on_wall_street', 10, 'Diversificação Moderada', 'Moderate Diversification', 'Possua 3-10 ações em portfólio pessoal. Menos que 3 é arriscado. Mais que 10 é difícil acompanhar. Foque em qualidade, não quantidade.', 'Own 3-10 stocks in personal portfolio. Less than 3 is risky. More than 10 is hard to follow. Focus on quality, not quantity.', 'Capítulo 16', 'Diversifique moderadamente - 3-10 ações bem escolhidas.', 'Diversify moderately - 3-10 well-chosen stocks.'),
('one_up_on_wall_street', 11, 'Ignore Previsões', 'Ignore Predictions', 'Ninguém pode prever mercado ou economia. Ignore economistas e estrategistas. Foque em empresas individuais. Boas empresas prosperam em qualquer ambiente.', 'Nobody can predict market or economy. Ignore economists and strategists. Focus on individual companies. Good companies prosper in any environment.', 'Capítulo 17', 'Ignore previsões macro - foque em qualidade das empresas.', 'Ignore macro predictions - focus on company quality.'),
('one_up_on_wall_street', 12, 'Seja Paciente', 'Be Patient', 'Mercado é volátil no curto prazo. Não venda em pânico. Se empresa é boa e preço caiu, compre mais. Paciência é recompensada.', 'Market is volatile short-term. Don''t sell in panic. If company is good and price fell, buy more. Patience is rewarded.', 'Conclusão', 'Paciência e convicção em empresas de qualidade vencem.', 'Patience and conviction in quality companies win.');

-- The Essays of Warren Buffett (12 excerpts)
INSERT INTO wisdom_excerpts (book_key, excerpt_order, title_pt, title_en, content_pt, content_en, page_reference, key_takeaway_pt, key_takeaway_en) VALUES
('essays_warren_buffett', 1, 'Governança Corporativa', 'Corporate Governance', 'Acionistas são donos. Gestores são empregados. Mas frequentemente gestores agem como donos e tratam acionistas como empregados. Exija alinhamento de interesses.', 'Shareholders are owners. Managers are employees. But often managers act like owners and treat shareholders like employees. Demand alignment of interests.', 'Parte 1', 'Governança deve alinhar interesses de gestores e acionistas.', 'Governance should align manager and shareholder interests.'),
('essays_warren_buffett', 2, 'Círculo de Competência', 'Circle of Competence', 'Conheça limites de seu conhecimento. Invista apenas dentro de seu círculo de competência. Não importa quão grande é o círculo, mas que você saiba onde estão as bordas.', 'Know limits of your knowledge. Invest only within your circle of competence. Doesn''t matter how big circle is, but that you know where edges are.', 'Parte 2', 'Fique dentro de seu círculo de competência.', 'Stay within your circle of competence.'),
('essays_warren_buffett', 3, 'Valor Intrínseco', 'Intrinsic Value', 'Valor intrínseco é fluxo de caixa futuro descontado a valor presente. Simples conceitualmente, difícil na prática. Requer estimativas de futuro incerto.', 'Intrinsic value is future cash flow discounted to present value. Simple conceptually, difficult in practice. Requires estimates of uncertain future.', 'Parte 2', 'Valor intrínseco é fluxo de caixa futuro descontado.', 'Intrinsic value is discounted future cash flow.'),
('essays_warren_buffett', 4, 'Margem de Segurança', 'Margin of Safety', 'Compre com desconto significativo sobre valor intrínseco. Margem de segurança protege contra erros de análise. Quanto maior incerteza, maior margem necessária.', 'Buy at significant discount to intrinsic value. Margin of safety protects against analysis errors. Greater uncertainty requires larger margin.', 'Parte 2', 'Sempre compre com margem de segurança substancial.', 'Always buy with substantial margin of safety.'),
('essays_warren_buffett', 5, 'Moats Econômicos', 'Economic Moats', 'Empresas com moats (fossos) mantêm vantagens competitivas. Procure marcas fortes, economias de escala, efeitos de rede, custos de mudança. Moats protegem lucros.', 'Companies with moats maintain competitive advantages. Look for strong brands, economies of scale, network effects, switching costs. Moats protect profits.', 'Parte 3', 'Invista em empresas com fossos econômicos duráveis.', 'Invest in companies with durable economic moats.'),
('essays_warren_buffett', 6, 'Gestão de Capital', 'Capital Management', 'Gestão deve alocar capital sabiamente. Reinvestir em negócio se retornos são altos. Caso contrário, retornar aos acionistas via dividendos ou recompras.', 'Management should allocate capital wisely. Reinvest in business if returns are high. Otherwise, return to shareholders via dividends or buybacks.', 'Parte 3', 'Alocação de capital disciplinada cria valor.', 'Disciplined capital allocation creates value.'),
('essays_warren_buffett', 7, 'Contabilidade', 'Accounting', 'Contabilidade é linguagem dos negócios. Mas pode ser manipulada. Examine notas de rodapé. Desconfie de ajustes frequentes e complexidade excessiva.', 'Accounting is language of business. But it can be manipulated. Examine footnotes. Distrust frequent adjustments and excessive complexity.', 'Parte 4', 'Entenda contabilidade mas desconfie de manipulações.', 'Understand accounting but distrust manipulations.'),
('essays_warren_buffett', 8, 'Aquisições', 'Acquisitions', 'Maioria das aquisições destroi valor para compradores. Gestores pagam demais por ego. Evite empresas que fazem aquisições frequentes. Crescimento orgânico é melhor.', 'Most acquisitions destroy value for buyers. Managers overpay for ego. Avoid companies making frequent acquisitions. Organic growth is better.', 'Parte 5', 'Aquisições frequentemente destroem valor - seja cético.', 'Acquisitions often destroy value - be skeptical.'),
('essays_warren_buffett', 9, 'Investimento vs. Especulação', 'Investment vs. Speculation', 'Investimento analisa valor e compra com margem de segurança. Especulação aposta em movimentos de preço. Seja investidor, não especulador.', 'Investment analyzes value and buys with margin of safety. Speculation bets on price movements. Be investor, not speculator.', 'Parte 6', 'Invista com base em valor, não especule em preços.', 'Invest based on value, don''t speculate on prices.'),
('essays_warren_buffett', 10, 'Derivativos', 'Derivatives', 'Derivativos são armas de destruição em massa financeira. Complexidade esconde riscos. Evite empresas com exposição significativa a derivativos.', 'Derivatives are weapons of mass financial destruction. Complexity hides risks. Avoid companies with significant derivatives exposure.', 'Parte 7', 'Derivativos complexos escondem riscos enormes.', 'Complex derivatives hide enormous risks.'),
('essays_warren_buffett', 11, 'Impostos', 'Taxes', 'Impostos são custo significativo. Mas não deixe cauda (impostos) abanar cachorro (decisões de investimento). Foque em retornos após impostos de longo prazo.', 'Taxes are significant cost. But don''t let tail (taxes) wag dog (investment decisions). Focus on long-term after-tax returns.', 'Parte 8', 'Considere impostos mas não deixe dominar decisões.', 'Consider taxes but don''t let them dominate decisions.'),
('essays_warren_buffett', 12, 'Paciência e Disciplina', 'Patience and Discipline', 'Investimento bem-sucedido requer paciência para esperar oportunidades e disciplina para agir quando aparecem. Não force investimentos. Espere fat pitches.', 'Successful investing requires patience to wait for opportunities and discipline to act when they appear. Don''t force investments. Wait for fat pitches.', 'Conclusão', 'Paciência para esperar e disciplina para agir são essenciais.', 'Patience to wait and discipline to act are essential.');

-- ============================================
-- END OF SEED DATA
-- Total: 15 books, 180 excerpts
-- ============================================
